# Generated by Django 3.2.9 on 2022-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kursun adini yaziniz', max_length=200, unique=True, verbose_name='Kurs Adi')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='courses/icardi.jpg', upload_to='courses/%Y%m/&d/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
